module.exports = {
  extend: require('lodash-node/modern/objects/assign'),
  defaults: require('lodash-node/modern/objects/defaults'),
  rest: require('lodash-node/modern/arrays/rest'),
  object: require('lodash-node/modern/arrays/zipObject'),
  omit: require('lodash-node/modern/objects/omit'),
  values: require('lodash-node/modern/objects/values'),
  isNull: require('lodash-node/modern/objects/isNull'),
  isArray: require('lodash-node/modern/objects/isArray'),
  isString: require('lodash-node/modern/objects/isString'),
  isObject: require('lodash-node/modern/objects/isObject'),
  isUndefined: require('lodash-node/modern/objects/isUndefined'),
  map: require('lodash-node/modern/collections/map'),
  each: require('lodash-node/modern/collections/forEach'),
  where: require('lodash-node/modern/collections/where'),
  every: require('lodash-node/modern/collections/every'),
  invoke: require('lodash-node/modern/collections/invoke'),
  toArray: require('lodash-node/modern/collections/toArray'),
  bind: require('lodash-node/modern/functions/bind'),
  createCallback: require('lodash-node/modern/functions/createCallback')
};