require 'rubygems'
require 'json'
require 'yaml'

task :update_version do
  version = JSON.parse(File.read('../package.json'))['version']
  site_config = YAML.load_file('_config.yml')
  if site_config['current_version'] != version
    site_config['current_version'] = version
    File.open('_config.yml', 'w+') { |f| f.write(site_config.to_yaml) }
  end
end

task :release => [:update_version] do
  system "jekyll build -d ../../marty-gh-pages"
  File.open('../../marty-gh-pages/CNAME', 'w+') { |f| f.write('martyjs.org') }
end

task :release_version => [:update_version] do
  site_config = YAML.load_file('_config.yml')

  system "jekyll build -d ../../marty-gh-pages/v/#{site_config['current_version']}"
  File.open('../../marty-gh-pages/CNAME', 'w+') { |f| f.write('martyjs.org') }
end